[package]
name = "cargo-newvsc"
version = "0.1.1"
authors = ["Adam Smith <adamsmith2708@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed="5.2.0"